### ISSUE TITLE
`stempo-common` 모듈 테스트 코드 작성

### ISSUE THREAD

**Issue by limehee** [KKKK-Stempo/stempo-server#76]
### Description
`stempo-common` 모듈의 공통 유틸리티 및 DTO 관련 단위 테스트를 작성하여 코드의 안정성을 확보합니다.

### Tasks
- [x] **DTO 단위 테스트**: 여러 모듈에서 공통으로 사용하는 DTO 객체의 독립적인 단위 테스트 작성.
- [x] **Util 클래스 단위 테스트**: 공통적으로 사용하는 유틸리티 클래스의 독립적인 단위 테스트 작성.
- [x] **Config 클래스 단위 테스트**: 모든 구성 클래스의 속성과 의존성이 정상적으로 주입되는지 확인하는 단위 테스트 작성.
