### ISSUE TITLE
`stempo-infrastructure` 모듈 테스트 코드 작성

### ISSUE THREAD

**Issue by limehee** [KKKK-Stempo/stempo-server#78]
### Description
stempo-infrastructure 모듈의 외부 시스템과의 통신, 데이터베이스 접근 및 설정 관련 로직을 검증하는 테스트 코드를 작성합니다. 파일 처리 및 외부 서비스 통신 기능이 정상적으로 작동하는지 확인합니다.

### Tasks
- [x] 외부 시스템과의 통신 테스트
- [x] 데이터베이스 접근 테스트
- [x] 파일 처리 및 외부 서비스 통신 로직 검증
