### ISSUE TITLE
`stempo-auth` 모듈 테스트 코드 작성

### ISSUE THREAD

**Issue by limehee** [KKKK-Stempo/stempo-server#79]
### Description
`stempo-auth` 모듈의 인증/인가 로직과 Spring Security 관련 테스트 코드를 작성하여 인증 관련 기능이 올바르게 동작하는지 검증합니다. JwtToken 발급 및 검증 로직을 포함한 주요 보안 기능을 테스트합니다.

### Tasks
- [x] 인증/인가 관련 유닛 테스트 작성
- [x] Spring Security 설정 검증
- [x] 로그인 및 토큰 발급 기능 테스트
- [x] 유틸리티 클래스 테스트
