### ISSUE TITLE
`stempo-application` 모듈 테스트 코드 작성

### ISSUE THREAD

**Issue by limehee** [KKKK-Stempo/stempo-server#80]
### Description
`stempo-application` 모듈의 서비스 계층과 데이터 처리 로직을 테스트하기 위한 유닛 테스트 및 통합 테스트를 작성합니다. 이를 통해 전체 애플리케이션의 기능을 검증하고 안정성을 확보합니다.

### Tasks
- [x] 서비스 계층의 유닛 테스트 작성
- [x] 데이터 처리 로직에 대한 테스트 작성
- [x] 통합 테스트로 주요 기능 검증
