### ISSUE TITLE
`stempo-api` 모듈 테스트 코드 작성

### ISSUE THREAD

**Issue by limehee** [KKKK-Stempo/stempo-server#81]
### Description
`stempo-api` 모듈의 API 엔드포인트를 검증하기 위한 통합 테스트 코드를 작성합니다. 이를 통해 API의 안정성을 확보하고, 예상치 못한 오류를 방지합니다.

### Tasks
- [x] `WebMvcTest`를 활용한 API 컨트롤러 테스트 작성
- [x] 사용자 정의 예외 제거 및 예외 상수화 처리
- [x]  `annotation`, `config`, `interceptor`, `support` 패키지에 대한 단위 테스트 작성
